// salespro-quickdraw — Acme Motors 2026 sample brand data
// ----------------------------------------------------------------------
// This is the sample data shipped with the OSS framework. All content is
// fictional. Acme Motors is not a real brand. Competitor names (Bedrock,
// Helio, Summit Peak, Crestwood, Aurora) are invented. Pricing and specs
// are illustrative, sized to feel plausible at a $30-50K price band.
//
// To customize for your own brand:
//   1. Read PROMPT.md
//   2. Replace this file using the AI-assisted walkthrough
//   3. Keep the shape — index.html depends on these keys
// ----------------------------------------------------------------------

window.BRAND_DATA = {
  BRAND_META: {
    // === Brand identity (PWA + HTML <head>) ===
    appName: 'Acme Motors 2026',
    shortName: 'Acme 26',
    htmlTitle: 'Acme Motors 2026',
    htmlDescription: 'Acme Motors 2026 sales app: floor reference + trim-by-trim trainer for the full 2026 lineup.',
    appleTitle: 'Acme 26',
    // === In-app surfaces ===
    dealerName: 'Acme Motors',
    floorEyebrow: 'Acme Motors · Sales Floor',
    standardsSubtitle: 'every Acme on the lot',
    trainerEyebrow: 'Acme Motors · Sales Training',
    modelYear: '2026',
    modelYearShort: '2026',
    floorHeadlineHTML: '2026 <span class="italic font-normal">Lineup</span> Reference',
    // === Footers / disclaimers ===
    trainerFooter: 'Pricing from Acme 2026 reference card · Competitor specs verified May 2026 · Always re-verify pricing in your DMS before quoting · Tow ratings require properly equipped trailer hitch · For Retailer Use Only',
    legalDisclaimer: 'Sample fictional data for demonstration. Replace with your own verified brand sources.',
    // === Defaults ===
    defaultModel: 'voyager',
    // === Storage key prefix ===
    storagePrefix: 'quickdraw',
  },

  LINEUP: [
    {
      id: 'voyager',
      name: 'Voyager',
      segment: 'Mid-Size SUV · 2-Row',
      note: 'New 7th gen. Standard AWD across the line. 11.6" touchscreen + 12.3" cluster STD. 260hp turbo on XT trims.',
      trims: [
        { name: 'Base',         msrp: 33495, powertrain: 'gas',   badges: [],                       features: 'AWD STD, 17" alloy, cloth, AcmeAssist driver-assist suite STD' },
        { name: 'Premium',      msrp: 36895, powertrain: 'gas',   badges: ['volume'],               features: '+18" wheels, heated front, power liftgate, wireless charge' },
        { name: 'Limited',      msrp: 41995, powertrain: 'gas',   badges: [],                       features: '+leather, premium 12-speaker audio, moonroof, heated rear, nav' },
        { name: 'Limited XT',   msrp: 44495, powertrain: 'turbo', badges: ['turbo'],                features: 'TURBO 260hp, 19" dark, surround camera, dual exhaust' },
        { name: 'Adventure',    msrp: 44995, powertrain: 'turbo', badges: ['turbo','wilderness','tow'], features: 'TURBO, 9.4" clearance, AT tires, bronze accents, 3,500 lb tow' },
        { name: 'Touring XT',   msrp: 47995, powertrain: 'turbo', badges: ['turbo','flag'],         features: 'Flagship. Nappa, vented seats, hands-free hwy assist, smart mirror.' },
      ]
    },
    {
      id: 'pioneer',
      name: 'Pioneer',
      segment: 'Compact SUV · 2-Row',
      note: '6th gen. New Adventure trim. Hybrid added. AcmeAssist + cabin attention camera STD on every trim.',
      trims: [
        { name: 'Base',           msrp: 28995, powertrain: 'gas',    badges: [],                     features: 'Cloth, dual 7" displays, 8.7" ground clearance, AcmeAssist STD' },
        { name: 'Premium',        msrp: 30995, powertrain: 'gas',    badges: ['volume'],             features: '+11.6" screen, pano roof, heated front, terrain modes — volume trim' },
        { name: 'Sport',          msrp: 33495, powertrain: 'gas',    badges: [],                     features: '+bronze accents, 19" dark, sport-tuned suspension, sport cloth' },
        { name: 'Limited',        msrp: 34995, powertrain: 'gas',    badges: [],                     features: '+leather, power liftgate, blind-spot, heated rear' },
        { name: 'Adventure',      msrp: 35995, powertrain: 'gas',    badges: ['wilderness','tow'],   features: '9.2" clearance, AT tires, terrain dual-mode, copper · 3,500 lb tow' },
        { name: 'Touring',        msrp: 38995, powertrain: 'gas',    badges: [],                     features: '+19" wheels, 360 camera, vented seats, heated rear, built-in nav' },
        { name: 'Premium Hybrid', msrp: 33495, powertrain: 'hybrid', badges: ['hybrid'],             features: '194hp combined, 12.3" cluster, nav STD, power liftgate · ~36 MPG' },
        { name: 'Touring Hybrid', msrp: 40995, powertrain: 'hybrid', badges: ['hybrid','flag'],      features: 'Top hybrid. Loaded comfort + tech.' },
      ]
    },
    {
      id: 'sprout',
      name: 'Sprout',
      segment: 'Subcompact SUV',
      note: 'All trims share new 2.5L 180hp. Hybrid joins for 2026 (~38% better city MPG). Adventure trim returns.',
      trims: [
        { name: 'Base',           msrp: 25995, powertrain: 'gas',    badges: [],                   features: '17" alloy, dual 7" displays, 8.7" clearance, AWD STD' },
        { name: 'Premium',        msrp: 27495, powertrain: 'gas',    badges: [],                   features: '+11.6" screen, all-weather pkg, wireless charging' },
        { name: 'Sport',          msrp: 30295, powertrain: 'gas',    badges: [],                   features: '+yellow accents, 18" dark, sport cloth, LED signal mirrors' },
        { name: 'Limited',        msrp: 32495, powertrain: 'gas',    badges: [],                   features: '+leather, blind-spot, attention camera, heated wheel' },
        { name: 'Adventure',      msrp: 33495, powertrain: 'gas',    badges: ['wilderness','tow'], features: '9.2" clearance, AT tires, terrain dual-mode, 3,500 lb tow' },
        { name: 'Sport Hybrid',   msrp: 33995, powertrain: 'hybrid', badges: ['hybrid'],           features: '12.3" cluster, blind-spot, moonroof STD · 194hp combined' },
        { name: 'Limited Hybrid', msrp: 34995, powertrain: 'hybrid', badges: ['hybrid','flag'],    features: 'Limited content + premium audio STD' },
      ]
    },
    {
      id: 'summit',
      name: 'Summit',
      segment: '3-Row SUV · 7 or 8-Pass',
      note: 'Refresh. New Bronze Edition. Tow rating bumped to 5,000 lb. All trims 260hp 2.4L turbo.',
      trims: [
        { name: 'Premium',         msrp: 41995, powertrain: 'turbo', badges: ['turbo','3-row','tow'], features: 'Black 18" wheels, heated front, fog, power liftgate (7 or 8-pass)' },
        { name: 'Limited',         msrp: 48495, powertrain: 'turbo', badges: ['turbo','3-row','tow'], features: '+leather, 20" wheels, pano roof, heated rear, surround camera, nav' },
        { name: 'Bronze Edition',  msrp: 49495, powertrain: 'turbo', badges: ['turbo','3-row','tow'], features: 'Limited + bronze 20" / accents, captain seats STD' },
        { name: 'Touring',         msrp: 51495, powertrain: 'turbo', badges: ['turbo','3-row','tow'], features: '+Nappa, vented seats, wood trim, smart mirror, 7-pass captain' },
        { name: 'Onyx Touring',    msrp: 52495, powertrain: 'turbo', badges: ['turbo','3-row','tow','flag'], features: 'Touring + black-out exterior, 20" black wheels' },
      ]
    },
    {
      id: 'velocity',
      name: 'Velocity',
      segment: 'Performance Sedan · AWD',
      note: 'Base returns. All trims 271hp 2.4L turbo. AcmeAssist STD even on manual transmission trims. Limited-run Spectrum edition (350 units).',
      trims: [
        { name: 'Base',          msrp: 31995, powertrain: 'turbo', badges: ['turbo'],            features: '18" alloy STD, keyless STD, summer tires · MT only' },
        { name: 'Premium',       msrp: 33495, powertrain: 'turbo', badges: ['turbo'],            features: '+heated front, fog, deicer, spoiler — daily-livable Velocity' },
        { name: 'Limited 6MT',   msrp: 38495, powertrain: 'turbo', badges: ['turbo'],            features: '+nav, premium audio, 10-way power, blind-spot, moonroof, leather' },
        { name: 'Limited Auto',  msrp: 39495, powertrain: 'turbo', badges: ['turbo'],            features: 'Limited with paddle-shift auto (+$1,000)' },
        { name: 'GT',            msrp: 44495, powertrain: 'turbo', badges: ['turbo'],            features: 'Recaro, adaptive dampers, 12.3" cluster · Auto only — no MT' },
        { name: 'Track Spec',    msrp: 44495, powertrain: 'turbo', badges: ['turbo'],            features: 'Track-tuned dampers, Brembo brakes, summer Potenza, 19", Recaro · MT only' },
        { name: 'Spectrum',      msrp: 45995, powertrain: 'turbo', badges: ['turbo','limited-run'], features: '350 UNITS · Track Spec + Spectrum Orange paint, matte black 19" · MT only' },
      ]
    },
  ],

  PACKAGES: {
    voyager: {
      'Base': [],
      'Premium': [
        { code: '13', add: 2270, source: 'Acme Retail · Aug 2025',
          features: ['Rain-sensing wipers', 'Built-in navigation', 'Heated steering wheel', 'Power moonroof', 'Wireless charger'] },
      ],
      'Limited': [],
      'Limited XT': [],
      'Adventure': [
        { code: '22', add: 2045, source: 'Acme Retail · Aug 2025',
          features: ['Power moonroof', 'Built-in navigation', 'Surround View Monitor'] },
        { code: '23', add: 4090, source: 'Acme Retail · Aug 2025',
          features: ['Power moonroof', 'Built-in navigation', 'Surround View Monitor', 'Nappa leather w/ copper stitch', 'Ventilated front seats', '12-way power memory driver seat', '8-way power passenger seat'] },
      ],
      'Touring XT': [],
    },
    pioneer: {
      'Base': [],
      'Premium': [
        { code: '15', add: 1200, source: 'Acme Retail · Aug 2025',
          features: ['Power liftgate', 'Blind-spot detection w/ rear cross-traffic alert'] },
      ],
      'Sport': [
        { code: '24', add: 1700, source: 'Acme Retail · Aug 2025',
          features: ['Premium 11-speaker audio', 'Power liftgate', 'Reverse automatic braking'] },
      ],
      'Limited': [
        { code: '42', add: 1600, source: 'Acme Retail · Aug 2025',
          features: ['Premium 11-speaker audio', 'Built-in navigation', 'Reverse automatic braking'] },
      ],
      'Adventure': [],
      'Touring': [],
      'Premium Hybrid': [],
      'Touring Hybrid': [],
    },
    sprout: {
      'Base': [],
      'Premium': [
        { code: '11', add: 1450, source: 'Acme Retail · Jul 2025',
          features: ['All-weather package (heated seats, mirrors, wiper deicer)', 'Wireless charging'] },
      ],
      'Sport': [],
      'Limited': [],
      'Adventure': [],
      'Sport Hybrid': [],
      'Limited Hybrid': [],
    },
    summit: {
      'Premium': [],
      'Limited': [],
      'Bronze Edition': [],
      'Touring': [],
      'Onyx Touring': [],
    },
    velocity: {
      'Base': [],
      'Premium': [],
      'Limited 6MT': [],
      'Limited Auto': [],
      'GT': [],
      'Track Spec': [],
      'Spectrum': [],
    },
  },

  PACKAGE_COVERAGE: {
    voyager: 'complete',
    pioneer: 'complete',
    sprout: 'partial',
    summit: 'none',
    velocity: 'none',
  },

  PAINT: {
    voyager:  { colors: ['Stonebrook Pearl', 'Deep Pine Pearl'],                          add: 395, source: 'Acme Retail · Aug 2025' },
    pioneer:  { colors: ['Stonebrook Pearl', 'Daybreak Blue Pearl'],                      add: 395, source: 'Acme Retail · Aug 2025' },
    sprout:   { colors: ['Alpine Green', 'Spectrum Yellow Pearl', 'Sand Dune Pearl'],     add: 395, source: 'Acme Retail · Jul 2025' },
    summit:   { colors: ['Crystal Black', 'Crystal White Pearl', 'Magnetite Gray', 'Crimson Red Pearl', 'Autumn Green', 'Sapphire Blue Pearl', 'Mahogany Brown Pearl'], add: 0, source: 'Acme Lineup Matrix · Mar 2026', note: 'all colors standard — no upcharge' },
    velocity: { colors: ['Spectrum Orange', 'Galaxy Purple Pearl'],                        add: 395, source: 'Acme Retail · Jan 2026' },
  },

  TRIM_DETAIL: {
    voyager: {
      'Premium': {
        configs: ['5-Passenger'],
        audio: { system: 'Acme 11.6" Multimedia Plus', speakers: 6, brand: null, wattage: null, navigation: false, sxm: 'SatRadio + Travel Link (3-mo trial)' },
        keyStandard: [
          '2.5L Boxer · 180 hp / 178 lb-ft',
          'CVT · 8-speed manual mode w/ paddles',
          'Acme Symmetrical AWD STD',
          '18" Alloy · 235/60 R18 All-Season',
          'AcmeAssist (stereo-camera ACC + lane centering + emergency stop)',
          'Cabin attention camera STD',
          'Blind-Spot Detection + Rear Cross-Traffic + Reverse Auto Braking',
          'LED Steering-Responsive Headlights · LED Fog · High Beam Assist',
          '11.6" Multimedia Plus · Wireless CarPlay / Android Auto',
          '8-Way Power Driver Seat',
          'Heated Steering Wheel · Heated Front Seats · Heated Mirrors',
          'Power Liftgate w/ Auto-Close + Height Memory',
          'Keyless Access + Push-Button Start',
        ],
        exteriorColors: ['Crystal Black', 'Crystal White Pearl', 'Magnetite Gray', 'Stonebrook Pearl', 'Deep Pine Pearl'],
        interior: ['Black Cloth w/ Silver Stitching'],
      },
      'Limited': {
        addsFrom: 'Premium',
        configs: ['5-Passenger'],
        audio: { system: 'Acme 11.6" Multimedia w/ Navigation', speakers: 12, brand: 'Acme Audio', wattage: 576, navigation: true, sxm: 'SatRadio + Travel Link + Traffic (3-yr w/ nav)' },
        keyAdds: [
          '19" Dark Gray Machine Finish · 235/55 R19',
          'Perforated Leather w/ Silver Stitching',
          'Terrain Dual-Mode w/ Hill Descent Control',
          '12-Way Power Driver w/ Memory · 4-Way Lumbar',
          'Surround View Monitor',
          '12-speaker premium audio · 576W',
          'Panoramic Power Moonroof w/ Sunshade',
          'Power-Folding Mirrors w/ Memory',
          'Heated Outboard Rear Seats',
          'Chrome Rear Badges',
        ],
        exteriorColors: ['Crystal Black', 'Crystal White Pearl', 'Magnetite Gray', 'Crimson Red Pearl', 'Sapphire Blue Pearl', 'Mahogany Brown Pearl'],
        interior: ['Slate Black Leather', 'Warm Ivory Leather'],
      },
      'Touring XT': {
        addsFrom: 'Limited',
        configs: ['5-Passenger'],
        audio: 'Same as Limited',
        keyAdds: [
          '260hp 2.4L Turbo Boxer · 277 lb-ft',
          'Nappa Leather w/ Bronze Stitching',
          'Ventilated Front Seats',
          'Acme Highway Hands-Free Assist',
          'Smart Mirror w/ Camera Feed',
          'Digital Rearview Mirror',
          '19" Polished Wheels',
          'Dual Exhaust',
        ],
        exteriorColors: ['Crystal Black', 'Crystal White Pearl', 'Magnetite Gray', 'Sapphire Blue Pearl', 'Mahogany Brown Pearl'],
        interior: ['Nappa Slate Black', 'Nappa Warm Ivory'],
      },
    },
    pioneer: {
      'Premium': {
        configs: ['5-Passenger'],
        audio: { system: 'Acme 11.6" Multimedia', speakers: 6, brand: null, wattage: null, navigation: false, sxm: 'SatRadio (3-mo trial)' },
        keyStandard: [
          '2.5L Boxer · 180 hp / 178 lb-ft',
          'CVT · 7-speed manual mode w/ paddles',
          'Acme Symmetrical AWD STD',
          '17" Alloy · 225/60 R17 All-Season',
          'AcmeAssist driver-assist suite STD',
          'Cabin attention camera STD',
          '11.6" Multimedia · Wireless CarPlay / Android Auto',
          'Panoramic Power Moonroof w/ Sunshade',
          'Heated Front Seats · Heated Mirrors',
          'Terrain Mode (snow/dirt)',
          'LED Headlights · High Beam Assist',
        ],
        exteriorColors: ['Crystal Black', 'Crystal White Pearl', 'Magnetite Gray', 'Daybreak Blue Pearl', 'Autumn Green'],
        interior: ['Black Cloth'],
      },
      'Limited': {
        addsFrom: 'Premium',
        configs: ['5-Passenger'],
        audio: { system: 'Acme 11.6" Multimedia w/ Navigation', speakers: 11, brand: 'Acme Audio', wattage: 440, navigation: true, sxm: 'SatRadio + Traffic (3-yr w/ nav)' },
        keyAdds: [
          '18" Dark Machine Finish Wheels',
          'Perforated Leather Trimmed',
          'Power Liftgate w/ Height Memory',
          'Blind-Spot Detection + Rear Cross-Traffic Alert',
          'Terrain Dual-Mode w/ Hill Descent Control',
          '10-Way Power Driver w/ Memory',
          'Heated Rear Outboard Seats',
          'Built-in Navigation',
          '11-Speaker Acme Audio · 440W',
        ],
        exteriorColors: ['Crystal Black', 'Crystal White Pearl', 'Magnetite Gray', 'Daybreak Blue Pearl', 'Crimson Red Pearl'],
        interior: ['Slate Black Leather', 'Saddle Tan Leather'],
      },
    },
  },

  TRIM_DETAIL_SOURCE: 'Acme Model Information · 2026MY (fictional sample data)',

  FLOOR_TRIAGE: [
    { cue: 'Three rows',               walk: 'Summit. Voyager is 2-row only — don\'t try to stretch it.' },
    { cue: 'Tow over 3,500 lb',        walk: 'Voyager Adventure/XT or Summit (5,000 lb). Skip Pioneer.' },
    { cue: 'Best MPG',                 walk: 'Sprout Hybrid first (~42 mpg), then Pioneer Hybrid.' },
    { cue: 'Long highway commute',     walk: 'Voyager Touring XT — AcmeAssist + the bigger screen is the closer.' },
    { cue: 'Trail / camping / clearance', walk: 'Adventure trims: Sprout 8.7″ · Pioneer 9.2″ · Voyager 9.5″' },
    { cue: 'Manual + AWD performance', walk: 'Velocity Limited 6MT. Base $31,995.' },
    { cue: 'The limited-run one',      walk: 'Velocity Spectrum. Confirm allocation before you promise it.' },
    { cue: 'Performance sedan, AWD',   walk: 'Velocity. Nothing else in segment does AWD standard under $33K.' },
    { cue: 'Track day',                walk: 'Velocity Track Spec or GT. Not the standard Limited trims.' },
  ],

  TRAPS: [
    { title: 'Pioneer tow rating', detail: 'Most Pioneer trims tow 1,500 lb. Only the Adventure trim is rated higher. Do NOT quote the Adventure number as the Pioneer rating.' },
    { title: 'Voyager Touring XT pitch', detail: 'Same turbo as Limited XT. Touring is comfort + tech, not more power. Don\'t sell it as the faster one.' },
    { title: 'Summit entry price', detail: 'Summit starts at Premium ($41,995). There is no stripped base Summit — quoting a sub-$40K 3-row sets a number you can\'t hit.' },
  ],

  STANDARDS: [
    'Symmetrical AWD standard on every model — including the Velocity sedan',
    'AcmeAssist driver-assist suite STD on all trims',
    'Cabin attention camera STD across the lineup',
    '11.6″ touchscreen STD on Premium and above',
    'AcmeConnect concierge 5-year trial STD',
    '5yr/60k powertrain · 3yr/36k basic warranty',
  ],

  TRAINER_DATA: {
    voyager: {
      name: 'Voyager',
      segment: 'Mid-Size SUV · 2-Row',
      trims: [
        {
          id: 'base',
          name: 'Base',
          msrp: '$33,495',
          engine: '180hp 2.5L Boxer',
          tow: '2,700 lb',
          mpg: '26 / 32',
          tagline: 'Entry without entry-level. Standard AWD plus the full AcmeAssist stack at $33,495.',
          reasons: [
            { h: 'Symmetrical AWD at $33,495', d: 'Bedrock Motors Ranger\'s cheapest AWD trim is $45,800. That\'s an $12,305 gap for the same all-weather promise.' },
            { h: 'AcmeAssist + cabin attention camera STD', d: 'Stereo-camera collision avoidance plus a cabin camera that watches for distraction. Most rivals lock the cabin camera to upper trims.' },
            { h: '11.6" touchscreen + 12.3" cluster STD', d: 'Helio Atlas SE makes you climb to SEL ($35K+) for the curved display panel. You get the full screen package on the entry Voyager.' },
            { h: '5-year AcmeConnect concierge trial', d: 'Concierge, SOS, remote start, geofencing — 5 years included. Helio\'s connected trial is 3 years.' },
            { h: 'Voyager resale history', d: 'Voyager has out-held the segment average on residuals for over a decade. Real money at trade-in time.' },
          ],
          comps: [
            {
              tab: 'Helio Atlas SE',
              name: 'Helio Atlas SE',
              price: '$33,300 FWD · $35,100 AWD',
              wins: [
                'AWD standard (Atlas SE is FWD; AWD is +$1,800)',
                '5-yr AcmeConnect trial vs Helio\'s 3-yr connected service',
                'Cabin attention camera STD (not on Atlas SE)',
                'AcmeAssist stereo-camera braking system',
                'Larger 11.6" touchscreen STD vs Atlas\'s 8" base unit',
              ],
              loses: [
                '277 hp turbo available vs 180 hp base (Atlas has the muscle on upper trims)',
                'Available 3rd row (Voyager is 2-row only)',
                'Atlas XRT tows 4,500 lb vs Voyager\'s 2,700',
                'Helio 10/100 powertrain warranty vs Acme 5/60',
              ],
            },
            {
              tab: 'Bedrock Ranger',
              name: 'Bedrock Motors Ranger SX AWD',
              price: '$37,200',
              wins: [
                '$3,705 cheaper at base sticker',
                'Cabin attention camera STD',
                'More ground clearance (8.7" vs 8.1")',
                'Larger 11.6" touchscreen STD',
                'AcmeConnect 5-yr trial vs Bedrock\'s 12-mo trial',
              ],
              loses: [
                '42-44 mpg combined hybrid vs ~28 mpg gas Voyager',
                'All 2026 Rangers are hybrid — Voyager has no hybrid option',
                'Bedrock SafetyShield 4.0 (latest gen driver-assist)',
                'Bedrock hybrid reliability: 25+ years of segment data',
                '12.3" digital cluster + 10.5" touch STD',
              ],
            },
            {
              tab: 'Crestwood Drift',
              name: 'Crestwood Drift 2.5 S Premium AWD',
              price: '$34,400',
              wins: [
                'More cargo volume behind 2nd row',
                '2,700 lb tow vs Crestwood\'s 2,000 lb (non-turbo)',
                'AcmeAssist + attention camera STD',
                '5-yr AcmeConnect trial',
                '8.7" ground clearance vs Crestwood\'s ~8.1"',
                'Bigger touchscreen (11.6" vs 10.25")',
              ],
              loses: [
                'Best-in-class driving dynamics reputation',
                'More upscale interior materials at this price',
                'Same AWD standard (push)',
                'Available turbo (256hp) at higher trims',
                'Available hybrid powertrain',
              ],
            },
          ],
          say: 'Even at our entry trim, you get standard AWD, AcmeAssist, and the driver-monitoring camera. That combination doesn\'t exist at this price anywhere else.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'premium',
          name: 'Premium',
          msrp: '$36,895',
          engine: '180hp 2.5L Boxer',
          tow: '2,700 lb',
          mpg: '26 / 32',
          tagline: 'Volume trim. Heated front, power liftgate, wireless charge — at the price most rivals charge for base.',
          reasons: [
            { h: 'Heated front + power liftgate STD', d: 'Bedrock Ranger makes you climb to the SEL trim ($41,000) for both — that\'s a $4,105 gap.' },
            { h: '18" wheels + wireless charging STD', d: 'Atlas SEL ($36K+) just adds the wireless pad as an option on most regional packages.' },
            { h: 'AcmeAssist + attention camera carry over from Base', d: 'Nothing is paywalled into upper trims. The safety package is the same on Base and Touring XT.' },
            { h: 'AcmeConnect 5-yr trial', d: 'Concierge, SOS, remote start. Most rivals top out at 3 years on this trial.' },
            { h: 'Symmetrical AWD continuous engagement', d: 'Continuous power split — not a part-time clutch-pack like Bedrock\'s on-demand AWD. Engages instantly because it never disengages.' },
          ],
          comps: [
            {
              tab: 'Atlas SEL',
              name: 'Helio Atlas SEL AWD',
              price: '$38,700',
              wins: [
                '$1,805 cheaper for comparable content',
                'Symmetrical AWD vs Helio HTRAC clutch-based',
                'Voyager historically stronger on residuals',
                '5-yr AcmeConnect trial',
                'Power liftgate STD (Atlas SEL trim package required)',
              ],
              loses: [
                '277 hp turbo available vs 180 hp',
                'Hybrid powertrain available (Voyager 2026 has no hybrid)',
                'Helio 10/100 powertrain warranty vs Acme 5/60',
                'Optional 3rd row',
              ],
            },
            {
              tab: 'Ranger SEL',
              name: 'Bedrock Motors Ranger SEL AWD',
              price: '$41,000',
              wins: [
                '$4,105 cheaper than Ranger SEL',
                'Symmetrical AWD (continuous) vs Bedrock clutch-pack',
                'Heated front + wireless charge STD',
                'Cabin attention camera STD',
                '5-yr AcmeConnect trial',
              ],
              loses: [
                '255 hp hybrid combined vs 180 hp gas',
                '~36 mpg city hybrid vs ~26 mpg gas',
                'Larger interior + more cargo (Ranger is 2.7" longer)',
                'Bedrock 10-speed auto vs Acme CVT',
                'Bedrock TrailWatch camera on upper trims',
              ],
            },
            {
              tab: 'Drift Carbon',
              name: 'Crestwood Drift Carbon Edition AWD',
              price: '$38,400',
              wins: [
                '$1,505 cheaper',
                '8.7" ground clearance vs Crestwood\'s 8.1"',
                'More cargo + interior volume',
                'AcmeConnect 5-yr trial',
                'Larger touchscreen',
              ],
              loses: [
                'Crestwood interior trim more premium at same price',
                'Available 256hp turbo on upper trims',
                'Sharper steering feel reputation in segment',
                'Crestwood available hybrid',
                'Better hwy mpg (33 vs 32) — push',
              ],
            },
          ],
          say: 'Premium is the trim 70% of Voyager buyers walk out with — heated seats, power liftgate, wireless charging, and the full AcmeAssist suite. Atlas wants $1,800 more for the same content.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'limited',
          name: 'Limited',
          msrp: '$41,995',
          engine: '180hp 2.5L Boxer',
          tow: '2,700 lb',
          mpg: '25 / 31',
          tagline: 'Volume luxury trim. Leather, 12-speaker audio, nav, moonroof — all standard.',
          reasons: [
            { h: 'Leather + heated rear seats STD', d: 'Helio makes you walk up to Atlas Limited ($44,600 + $1,800 AWD = $46,400) for the same content.' },
            { h: '12-speaker premium audio STD', d: 'Premium audio at a $42K out-the-door price. Bedrock Ranger Limited doesn\'t include a premium audio brand at this trim.' },
            { h: 'Moonroof, power liftgate, built-in nav STD', d: 'Built-in nav, not phone-only. Stays working when cell signal dies on the back roads.' },
            { h: 'AcmeAssist carries over from Premium', d: 'No paywall on safety. Same suite on Base and Touring XT.' },
            { h: 'Symmetrical AWD + Terrain Dual-Mode STD', d: 'Continuous power split, not a clutch-pack. Engages instantly because it never disengages.' },
          ],
          comps: [
            {
              tab: 'Atlas Ltd',
              name: 'Helio Atlas Limited AWD',
              price: '$46,400',
              wins: [
                '$4,405 less for comparable luxury content',
                'Symmetrical AWD vs Helio HTRAC',
                'Voyager historically stronger on residuals',
                '5-yr AcmeConnect trial',
                'Built-in nav STD (Atlas requires premium pkg)',
              ],
              loses: [
                '277 hp turbo vs 180 hp',
                'Available hybrid (Voyager Limited has none)',
                'Helio 10/100 warranty vs Acme 5/60',
                'Optional 3rd row',
              ],
            },
            {
              tab: 'Crown Drift',
              name: 'Crestwood Crown Drift Touring',
              price: '$44,390',
              wins: [
                '$2,395 cheaper',
                '8.7" ground clearance vs Crown Drift\'s 6.7"',
                'Cabin attention camera STD',
                'More usable as a real SUV (Crown Drift is a lifted wagon)',
                '2,700 lb tow on both — push',
              ],
              loses: [
                '38 mpg combined hybrid vs 28 mpg',
                'Quieter at low speeds (electric-first hybrid)',
                'Standard leather + safety suite at entry price',
                'Crown badge prestige factor',
                'Crestwood hybrid reliability proven',
              ],
            },
            {
              tab: 'Ranger RTL',
              name: 'Bedrock Motors Ranger RTL AWD',
              price: '$46,200',
              wins: [
                '$4,205 cheaper than Ranger RTL',
                'Symmetrical AWD (continuous) vs Bedrock clutch-pack',
                '11.6" + 12.3" digital cockpit STD',
                'Cabin attention camera STD',
                '5-yr AcmeConnect trial',
              ],
              loses: [
                '285 hp V6 vs 180 hp (large power gap)',
                '5,000 lb tow vs 2,700 lb',
                'Ranger stretched 2.7" for cargo volume',
                'Bedrock 10-speed auto vs Acme CVT',
                'TrailWatch camera on upper RTL trims',
              ],
            },
          ],
          say: 'Limited gives you leather, premium audio, heated rear seats — for almost five grand less than an Atlas Limited with AWD.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'limitedxt',
          name: 'Limited XT',
          msrp: '$44,495',
          engine: '260hp 2.4L Turbo Boxer',
          tow: '3,500 lb',
          mpg: '21 / 29',
          tagline: 'Turbo torque + Limited luxury + surround camera. Under $45K.',
          reasons: [
            { h: '260hp turbo · 277 lb-ft at 2,000 RPM', d: 'Torque where you need it — merging, climbing, towing. Not a peaky high-RPM engine.' },
            { h: '3,500 lb tow with full luxury content', d: 'Same tow rating as Adventure, but with heated leather and premium audio. You don\'t choose between muscle and comfort.' },
            { h: 'Surround-view camera STD', d: 'Game-changer for tight parking, narrow trails, reading distance to bumpers in cities.' },
            { h: '19" dark wheels + dual exhaust', d: 'Limited content with the turbo look — for buyers who want muscle without screaming "off-road."' },
            { h: 'Still cheaper than the Ranger RTL', d: 'Ranger RTL ($46,200) tows more but loses on heated rear, leather, surround camera, and 4 mpg highway.' },
          ],
          comps: [
            {
              tab: 'Ranger RTL',
              name: 'Bedrock Motors Ranger RTL AWD',
              price: '$46,200',
              wins: [
                '$1,705 cheaper',
                'Surround-view camera + heated rear seats STD',
                'Better hwy mpg (29 vs ~25)',
                '11.6" + 12.3" digital cockpit STD (Ranger RTL has smaller cluster)',
                '5-yr AcmeConnect trial',
              ],
              loses: [
                '285 hp V6 vs 260 hp turbo I-4',
                '5,000 lb tow vs 3,500 lb',
                'Ranger stretched 2.7" for more cargo',
                'Bedrock 10-speed auto vs Acme CVT (preference call)',
              ],
            },
            {
              tab: 'Drift Turbo',
              name: 'Crestwood Drift 3.3 Turbo Preferred',
              price: '$43,780',
              wins: [
                'Surround-view camera STD (Drift Preferred lacks 360°)',
                '11.6" + 12.3" digital cockpit STD',
                'Higher ground clearance (8.7" vs Drift\'s lower stance)',
                '5-yr AcmeConnect trial',
                'Heated rear seats + leather STD',
              ],
              loses: [
                '280 hp inline-6 with 48V mild-hybrid (smoother power)',
                'More upscale interior materials',
                'Crestwood handling reputation',
                'Drift Premium Plus trim adds 360° camera',
                'AWD different character (rear-biased vs symmetrical)',
              ],
            },
            {
              tab: 'Atlas XRT',
              name: 'Helio Atlas XRT Turbo',
              price: '$45,800',
              wins: [
                '$1,305 cheaper',
                'Symmetrical AWD (continuous) vs HTRAC',
                'Surround camera STD',
                'Lower step-in height',
                '5-yr AcmeConnect trial',
              ],
              loses: [
                '277 hp turbo vs 260 hp — push',
                '4,500 lb tow vs 3,500 lb',
                'XRT trim has tow-specific cooling',
                'Helio 10/100 powertrain warranty',
                'Optional 3rd row available',
              ],
            },
          ],
          say: 'Limited XT is the Voyager that says "I want the turbo and the leather and the surround camera, but I don\'t want to look like I\'m going off-roading on Saturday." Same tow as Adventure, full Limited content.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'adventure',
          name: 'Adventure',
          msrp: '$44,995',
          engine: '260hp 2.4L Turbo Boxer',
          tow: '3,500 lb',
          mpg: '21 / 27',
          tagline: 'Turbo + 9.4" clearance + AT tires. The Voyager that earns the trim name.',
          reasons: [
            { h: '9.4" ground clearance + AT tires STD', d: 'Most rivals call themselves "off-road" with 8.1" clearance and street tires. Adventure ships ready.' },
            { h: '3,500 lb tow + turbo torque', d: '260hp + 277 lb-ft + 3,500 lb tow. Camper or boat ready out of the gate.' },
            { h: 'Terrain Dual-Mode + Hill Descent STD', d: 'Two-mode terrain logic (snow/dirt + deep snow/mud) — not a single "snow" toggle.' },
            { h: 'Bronze accents + copper stitch interior', d: 'Distinct visual identity. Doesn\'t look like a regular Voyager with a roof rack.' },
            { h: 'Cheaper than Ranger TrailSport', d: 'Ranger TrailSport tow + clearance package is $48,500. Adventure undercuts by $3,500.' },
          ],
          comps: [
            {
              tab: 'Ranger TrailSport',
              name: 'Bedrock Motors Ranger TrailSport',
              price: '$48,500',
              wins: [
                '$3,505 cheaper',
                'Terrain Dual-Mode (Ranger has single TrailWatch mode)',
                'Better hwy mpg (27 vs 24)',
                '5-yr AcmeConnect trial',
                'Symmetrical AWD continuous engagement',
              ],
              loses: [
                '285 hp V6 vs 260 hp turbo I-4',
                '5,000 lb tow vs 3,500 lb',
                'TrailWatch camera (front camera for crawling)',
                'Longer wheelbase + better cargo',
                'Bedrock branding for off-road buyers',
              ],
            },
            {
              tab: 'Atlas XRT',
              name: 'Helio Atlas XRT',
              price: '$45,800',
              wins: [
                '$805 cheaper',
                '9.4" clearance vs XRT\'s 8.3"',
                'AT tires STD (XRT has all-season)',
                'Terrain Dual-Mode',
                'Continuous AWD vs HTRAC clutch',
              ],
              loses: [
                '4,500 lb tow vs 3,500 lb',
                '277 hp turbo (slight power edge)',
                '3rd row available',
                'Helio 10/100 warranty',
                'XRT-specific bumper geometry',
              ],
            },
            {
              tab: 'Trail Peak',
              name: 'Summit Peak Trail',
              price: '$46,200',
              wins: [
                '$1,205 cheaper',
                'Continuous Symmetrical AWD',
                'Better hwy mpg',
                'Surround camera STD',
                '5-yr AcmeConnect trial',
              ],
              loses: [
                'Solid-axle rear (true off-road geometry)',
                'Locking rear differential available',
                'Higher payload rating',
                'Stronger off-road brand cachet',
                'Aftermarket support deeper',
              ],
            },
          ],
          say: 'Adventure isn\'t a sticker package. 9.4" clearance, AT tires, dual-mode terrain, turbo, 3,500 lb tow — and it\'s $3,500 less than Ranger TrailSport. If the customer actually goes off pavement, this is the one.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'touringxt',
          name: 'Touring XT',
          msrp: '$47,995',
          engine: '260hp 2.4L Turbo Boxer',
          tow: '3,500 lb',
          mpg: '21 / 29',
          tagline: 'Flagship. Nappa, vented seats, Highway Hands-Free Assist, smart mirror.',
          reasons: [
            { h: 'Highway Hands-Free Assist STD', d: 'Hands-off lane-centered driving on mapped highways. Not a hold-the-wheel adaptive cruise — actual hands-free.' },
            { h: 'Nappa leather + ventilated front', d: 'Cooled seats actually cool, not just "circulate cabin air." Real Peltier-element vented seats.' },
            { h: 'Smart Mirror w/ camera feed', d: 'Rear cargo blocked? Toggle the rearview to a rear-facing camera. Useful with kids, dogs, or rear cargo packed to the headliner.' },
            { h: '260hp turbo + 3,500 lb tow + flagship comfort', d: 'You don\'t pick between muscle and comfort. Touring XT has both.' },
            { h: 'Cheaper than Atlas Calligraphy', d: 'Atlas Calligraphy AWD is $50,800. Touring XT undercuts by $2,805 with comparable content.' },
          ],
          comps: [
            {
              tab: 'Atlas Cal',
              name: 'Helio Atlas Calligraphy AWD',
              price: '$50,800',
              wins: [
                '$2,805 cheaper',
                'Highway Hands-Free Assist (Atlas has Highway Drive Assist 2 — hands-on)',
                'Symmetrical AWD vs HTRAC',
                '5-yr AcmeConnect trial',
                'Smart Mirror + digital rearview',
              ],
              loses: [
                '277 hp turbo vs 260 hp — push',
                'Quilted Nappa + suede headliner',
                'Calligraphy interior materials more upscale',
                'Helio 10/100 warranty',
                '3rd row available',
              ],
            },
            {
              tab: 'Ranger Elite',
              name: 'Bedrock Motors Ranger Elite AWD',
              price: '$49,900',
              wins: [
                '$1,905 cheaper',
                'Highway Hands-Free vs hands-on',
                'Continuous Symmetrical AWD',
                'Smart Mirror STD',
                '5-yr AcmeConnect',
              ],
              loses: [
                '285 hp V6 vs 260 hp turbo',
                '5,000 lb tow vs 3,500 lb',
                'Elite trim Bose audio (premium-brand)',
                'TrailWatch front camera',
                'Bedrock 10-speed transmission',
              ],
            },
            {
              tab: 'Drift Signature',
              name: 'Crestwood Drift Signature 3.3 Turbo',
              price: '$50,300',
              wins: [
                '$2,305 cheaper',
                'Highway Hands-Free Assist',
                '9.4"-grade clearance vs Drift\'s lower stance',
                '5-yr AcmeConnect',
                'Vented seats STD',
              ],
              loses: [
                '340 hp inline-6 + 48V mild-hybrid (smoother)',
                'Signature interior materials',
                'Crestwood handling reputation',
                'Drift available hybrid',
                'AWD rear-biased character',
              ],
            },
          ],
          say: 'Touring XT is the only Voyager with Highway Hands-Free. That alone is the conversation for buyers spending hours on 95. Combine it with vented Nappa and turbo, and you\'re under what Atlas Calligraphy stickers at.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
      ],
    },

    pioneer: {
      name: 'Pioneer',
      segment: 'Compact SUV · 2-Row',
      trims: [
        {
          id: 'base',
          name: 'Base',
          msrp: '$28,995',
          engine: '180hp 2.5L Boxer',
          tow: '1,500 lb',
          mpg: '26 / 32',
          tagline: 'The compact SUV with all the safety tech at the entry price.',
          reasons: [
            { h: 'AcmeAssist + attention camera STD', d: 'Bedrock Trek\'s cabin attention camera doesn\'t arrive until the EX trim ($32K+). You get it at $28,995.' },
            { h: 'Symmetrical AWD STD', d: 'Atlas Compact base is FWD only. AWD adds $1,500. Pioneer is AWD out of the gate.' },
            { h: 'Dual 7" displays STD', d: 'Aurora Drift base ships with a single 7" screen. Pioneer Base has both the center display and a digital cluster.' },
            { h: '8.7" ground clearance STD', d: 'More than most rivals\' "Adventure" trims. Real winter capability.' },
            { h: '5-yr AcmeConnect trial', d: 'Concierge, SOS, remote start — five years included. Most rivals cap at three.' },
          ],
          comps: [
            {
              tab: 'Trek LX',
              name: 'Bedrock Motors Trek LX AWD',
              price: '$31,400',
              wins: [
                '$2,405 cheaper',
                'Cabin attention camera STD (Trek LX doesn\'t have it)',
                '8.7" ground clearance vs 7.8"',
                '5-yr AcmeConnect trial',
                'Symmetrical AWD continuous',
              ],
              loses: [
                'Trek bigger cargo bay (Pioneer 27 cu ft vs Trek 36)',
                'Bedrock 10-yr powertrain warranty',
                'Hybrid available (Pioneer Base is gas only)',
                'Bedrock SafetyShield 4.0 driver-assist',
              ],
            },
            {
              tab: 'Atlas Compact',
              name: 'Helio Atlas Compact SE AWD',
              price: '$28,800',
              wins: [
                'AcmeAssist + attention camera STD',
                'Larger dual-display cluster STD',
                '5-yr AcmeConnect trial',
                'Continuous AWD vs HTRAC',
                'Higher ground clearance',
              ],
              loses: [
                '$195 more (push)',
                'Helio 10/100 warranty vs Acme 5/60',
                'Bose audio available on SEL',
                'Available hybrid',
                'Helio shopping app integration',
              ],
            },
            {
              tab: 'Aurora Drift',
              name: 'Aurora Drift 2.5 S AWD',
              price: '$30,400',
              wins: [
                '$1,405 cheaper',
                'AcmeAssist + attention camera STD',
                '8.7" ground clearance',
                'Dual display STD',
                '5-yr AcmeConnect',
              ],
              loses: [
                'Aurora driving dynamics reputation',
                'Available 256hp turbo on upper trims',
                'More premium interior materials at this trim',
                'Aurora available hybrid',
                'Same AWD STD (push)',
              ],
            },
          ],
          say: 'Pioneer Base is the only compact SUV under $29K with AWD, AcmeAssist, the attention camera, and 8.7" clearance — all standard.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'premium',
          name: 'Premium',
          msrp: '$30,995',
          engine: '180hp 2.5L Boxer',
          tow: '1,500 lb',
          mpg: '26 / 32',
          tagline: 'Volume trim. Panoramic roof, heated front, terrain modes — at $31K.',
          reasons: [
            { h: 'Panoramic moonroof STD', d: 'Atlas Compact SEL ($33K+) makes you check the premium box for the pano roof.' },
            { h: '11.6" touchscreen STD', d: 'Bedrock Trek EX still ships with the 9" unit unless you pay for the tech pkg.' },
            { h: 'Heated front + terrain modes STD', d: 'Snow + dirt modes, not a single "snow" toggle. Heated cloth — leather not required.' },
            { h: 'AcmeAssist carries from Base', d: 'No paywall on safety. Same suite Base → Touring.' },
            { h: 'Continuous Symmetrical AWD', d: 'Engages instantly because it never disengages. Different feel than reactive clutch-pack systems.' },
          ],
          comps: [
            {
              tab: 'Trek EX',
              name: 'Bedrock Motors Trek EX AWD',
              price: '$33,900',
              wins: [
                '$2,905 cheaper',
                'Pano roof STD (Trek EX has standard moonroof only)',
                '11.6" screen STD',
                '5-yr AcmeConnect',
                'Cabin attention camera STD',
              ],
              loses: [
                'Trek bigger cargo bay',
                'Bedrock 10-yr powertrain warranty',
                'Hybrid available',
                'Bedrock SafetyShield 4.0 latest gen',
                'Trek Premium audio package available',
              ],
            },
            {
              tab: 'Atlas SEL',
              name: 'Helio Atlas Compact SEL AWD',
              price: '$33,100',
              wins: [
                '$2,105 cheaper',
                'Pano roof STD (Atlas SEL Premium Pkg required)',
                'Continuous AWD',
                '5-yr AcmeConnect',
                'Larger cargo behind 2nd row',
              ],
              loses: [
                'Helio 10/100 warranty',
                'Available turbo on upper trims',
                'Bose audio on SEL Premium',
                'Available hybrid',
                'Helio digital key',
              ],
            },
            {
              tab: 'Drift Carbon',
              name: 'Aurora Drift Carbon Edition AWD',
              price: '$32,800',
              wins: [
                '$1,805 cheaper',
                'AcmeAssist + attention camera STD',
                'Pano roof STD',
                '8.7" ground clearance',
                '5-yr AcmeConnect',
              ],
              loses: [
                'Carbon Edition trim styling',
                'Aurora handling reputation',
                'Available 256hp turbo',
                'More upscale interior materials',
                'Aurora hybrid available',
              ],
            },
          ],
          say: 'Premium is the trim most Pioneer buyers walk out with. Pano roof, heated front, full safety suite. Atlas Compact SEL wants $2,100 more for the same content.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'sport',
          name: 'Sport',
          msrp: '$33,495',
          engine: '180hp 2.5L Boxer',
          tow: '1,500 lb',
          mpg: '25 / 31',
          tagline: 'Bronze accents, sport-tuned suspension, 19" dark wheels. The Pioneer that doesn\'t look like everyone else\'s.',
          reasons: [
            { h: 'Bronze trim accents + bronze 19" wheels', d: 'Distinct from Premium and Limited visually. Buyers who want the SUV without looking like every other Pioneer in the lot.' },
            { h: 'Sport-tuned suspension', d: 'Stiffer dampers, quicker turn-in. Still rides livably — not a track car.' },
            { h: 'Sport cloth + LED accent lighting', d: 'Distinct interior trim. Not just badge-deep.' },
            { h: 'AcmeAssist carries from lower trims', d: 'No safety paywall. Sport gets the same package as Limited.' },
            { h: 'Cheaper than Trek EX-Sport', d: 'Bedrock Trek EX-Sport AWD is $35,800. Sport undercuts by $2,305.' },
          ],
          comps: [
            {
              tab: 'Trek EX-Sport',
              name: 'Bedrock Motors Trek EX-Sport AWD',
              price: '$35,800',
              wins: [
                '$2,305 cheaper',
                'Bronze styling distinct from other Pioneers',
                'Continuous Symmetrical AWD',
                '5-yr AcmeConnect',
                'Sport suspension genuinely tuned (Trek EX-Sport is appearance only)',
              ],
              loses: [
                'Trek EX-Sport hybrid powertrain available',
                'Trek bigger cargo bay',
                'Bedrock 10-yr warranty',
                'SafetyShield 4.0 driver-assist',
                'Trek EX-Sport Bose audio available',
              ],
            },
            {
              tab: 'Atlas N Line',
              name: 'Helio Atlas Compact N Line AWD',
              price: '$34,800',
              wins: [
                '$1,305 cheaper',
                'Continuous AWD',
                'Cabin attention camera STD',
                '5-yr AcmeConnect',
                '8.7" ground clearance',
              ],
              loses: [
                'N Line gets 277 hp turbo',
                'Helio 10/100 warranty',
                'N Line track-tuned electronic LSD',
                'More aggressive body kit',
                'Available hybrid (separate trim)',
              ],
            },
            {
              tab: 'Drift Sport',
              name: 'Aurora Drift Sport Edition AWD',
              price: '$33,200',
              wins: [
                'Push on price ($295 cheaper)',
                'AcmeAssist + attention camera STD',
                'Bronze accents distinct',
                'Pano roof STD',
                '5-yr AcmeConnect',
              ],
              loses: [
                'Aurora steering feel reputation',
                'Available 256hp turbo',
                'More upscale interior at same price',
                'Aurora hybrid available',
                'Sport Edition appearance pkg',
              ],
            },
          ],
          say: 'Sport is for the customer who wants the Pioneer but not the same Pioneer everyone in their neighborhood drives. Bronze 19s, sport suspension, sport cloth. $2,300 less than Trek EX-Sport.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
        {
          id: 'limited',
          name: 'Limited',
          msrp: '$34,995',
          engine: '180hp 2.5L Boxer',
          tow: '1,500 lb',
          mpg: '26 / 32',
          tagline: 'Leather, power liftgate, heated rear, blind-spot — under $35K.',
          reasons: [
            { h: 'Leather + heated rear STD', d: 'Trek Touring ($37,500) is the comparable Bedrock trim. Pioneer Limited undercuts by $2,505.' },
            { h: 'Power liftgate + memory STD', d: 'Atlas Compact Limited charges for the memory function as part of the convenience pkg.' },
            { h: 'Blind-spot + rear cross-traffic STD', d: 'Carry-over from AcmeAssist suite — no upcharge to get it.' },
            { h: 'Terrain Dual-Mode + Hill Descent STD', d: 'Same off-road logic as Adventure trim, in a luxury wrapper.' },
            { h: 'Continuous Symmetrical AWD', d: 'No clutch-pack lag. Engages because it\'s already engaged.' },
          ],
          comps: [
            {
              tab: 'Trek Touring',
              name: 'Bedrock Motors Trek Touring AWD',
              price: '$37,500',
              wins: [
                '$2,505 cheaper',
                'Heated rear + terrain dual-mode STD',
                'Continuous Symmetrical AWD',
                '5-yr AcmeConnect',
                'Cabin attention camera STD',
              ],
              loses: [
                'Trek bigger cargo bay (~9 cu ft more)',
                'Bedrock 10-yr powertrain warranty',
                'Hybrid available',
                'Trek Bose audio',
                'SafetyShield 4.0 latest gen',
              ],
            },
            {
              tab: 'Atlas Ltd',
              name: 'Helio Atlas Compact Limited AWD',
              price: '$36,900',
              wins: [
                '$1,905 cheaper',
                'Memory power liftgate STD',
                'Continuous AWD',
                '5-yr AcmeConnect',
                'Terrain dual-mode',
              ],
              loses: [
                'Helio 10/100 warranty',
                'Bose 12-speaker on Limited',
                'Atlas hybrid available',
                'Available 277 hp turbo',
                'Helio digital key',
              ],
            },
            {
              tab: 'Drift Premium',
              name: 'Aurora Drift Premium Plus AWD',
              price: '$36,200',
              wins: [
                '$1,205 cheaper',
                'AcmeAssist + attention camera STD',
                'Power liftgate w/ memory STD',
                '8.7" ground clearance',
                '5-yr AcmeConnect',
              ],
              loses: [
                'Aurora interior premium feel',
                'Bose available',
                'Available turbo on Premium Plus',
                'Aurora hybrid available',
                'Aurora handling',
              ],
            },
          ],
          say: 'Limited is leather + heated rear + power liftgate + blind-spot — for $2,500 less than Trek Touring. Same continuous AWD as the rest of the lineup.',
          verified: { date: '2026-05-23', sources: ['Acme Retail · Aug 2025'] },
        },
      ],
    },

    // Other models declare names + empty trims — Trainer renders a
    // placeholder ("see Floor Ref") and Floor mode still shows full lineup.
    sprout: {
      name: 'Sprout',
      segment: 'Subcompact SUV',
      trims: [],
    },
    summit: {
      name: 'Summit',
      segment: '3-Row SUV · 7 or 8-Pass',
      trims: [],
    },
    velocity: {
      name: 'Velocity',
      segment: 'Performance Sedan · AWD',
      trims: [],
    },
  },
};
